name: http_extensions_retry
description: An http extension that retries failed requests.
version: 0.1.1
homepage: https://github.com/aloisdeniel/http_extensions
author: aloisdeniel <alois.deniel@outlook.com>

environment:
  sdk: '>=2.2.0 <3.0.0'

dependencies:
  meta: ^1.1.6
  http: ^0.12.0+1
  http_extensions: ^0.1.0
  logging: ^0.11.3
